### ISSUE TITLE
Should be able to execute client side plugin while AHEAD

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1162]
When executing a server side plugin, it makes sense to block the use if the client is AHEAD since the server doesn't have the same state as the client (which is the target state of the plugin execution). However, this doesn't hold if the plugin is to be executed on the client as the client has all the necessary state for the plugin.

**Comment by pmeijer** [comment]
If the plugin forks locally from the client - it will proceed to make commits on it's own. Since the client is AHEAD there is no guarantee that the commit the plugin started from would have been persisted at the time the plugin's commit arrives.
(This is checked by the InterpreterManager for the default UI - if you know for sure that your plugin won't make any changes or you change the default save behavior - you can still invoke plugins directly via the client API)
