### ISSUE TITLE
webgme fails to render on microsoft edge

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme#1459]
webgme site continuously reloads on windows edge browser.

Details:
Microsoft Edge 40.15063.0.0

**Comment by finger563** [comment]
+1

**Comment by pmeijer** [comment]
I got the latest version of Edge now as well. And can confirm that it doesn't work. Right now I'm having issues debugging since edge insists on reloading the page.
I've looked around and there are some threads about Edge acting out like this on random webpages - but no particular cure for it. However since I can load the barebone webgme client w/o the UI. There are some pieces in out code that triggers the behavior. I will keep investigating..

**Comment by pmeijer** [comment]
Closed by #1637
