### ISSUE TITLE
Maximize split screen button blocks other UI elements when hidden

### ISSUE THREAD

**Issue by DWatkins** [webgme/webgme#1501]
![image](https://user-images.githubusercontent.com/455381/29880209-d379f0ca-8d6c-11e7-911e-745a479acf73.png)

When not using split screens the maximize button is hidden but still present, so any other objects in that same location cannot be interacted with.

**Comment by pmeijer** [comment]
1. Detach element when not in split mode.
2. Add API call on [IActivePanel](https://github.com/webgme/webgme/blob/master/src/client/js/PanelManager/IActivePanel.js) getMaximizerPlacement() -> `nw`, `ne`, `sw`, `se` (`ne` default), `hide`
3. Add maximize control in splitpanel dropdown.

Suggested actions

**Comment by pmeijer** [comment]
@finger563 any takes on this?

**Comment by finger563** [comment]
@pmeijer I think #1 and #3 should definitely be added, and #3 is great because when all else fails, it's where people will look (since it already has "remove current panel") aside from that getting the placement is great, and I'd be able to use that for my viz, but i'm not sure if that's helpful for all other visualizers.

More generally, what I might suggest is to actually have a toolbar that may contain more buttons (such as the "remove split panel" button, and a "minimize / restore size" button when in maximized mode) and expose the toolbar to the users so that my viz for instance can add my buttons there instead of just placing them myself.  It sounds like it would serve the similar purpose as the existing toolbar and it probably would but it does provide a nice way to have buttons that may always be clickable even if the viz is not selected (reducing the number of clicks).
