### ISSUE TITLE
Unable to import project - Docker container

### ISSUE THREAD

**Issue by BigDaddyKahuna** [webgme/webgme#1635]
Import Fails:
- Upper right menu -> click Import Project
- Create new project, add name
- Click import tab
- Select file from file chooser.
After selecting a file the file name immediately disappears in the field.
I see this in the output:

webgme   | 2018-09-13T22:27:22.059Z - error: [gme:server:standalone:middleware:BlobServer] Error: EACCES: permission denied, rename '/dockershare/blob-local-storage/wg-temp-8001/3d78efa5-14bf-9539-8fa2-6565530908de.tbf' -> '/dockershare/blob-local-storage/wg-content/10/de182b3522520fa52644d9c7c2a52b4762a935'

Deployment:
I have two containers, one for mongo and the  other for webgme.   Following is the Docker compose file contents:
version: '3'

services: 
  mongo:
    container_name: mongo
    image: mongo:3
    volumes:
     - C:\Docker\webgme\images\dockershare\db:c:\data\db
    networks:
      testing_net:
        ipv4_address: 172.30.1.2 
        
  web:
    environment:
      - GME_ADMIN=admin:admin
      - MONGO_PORT_27017_TCP_ADDR=172.30.1.2
      - MONGO_PORT_27017_TCP_PORT=27017
    container_name: webgme
    depends_on:
      - mongo
    image: webgme/webgme-org:2.17.0
    ports:
     - "8888:8001"
    volumes:
     - C:\Docker\webgme\images\dockershare:/dockershare
    networks:
      testing_net:
        ipv4_address: 172.30.1.1        
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
        
Might this be a permissions issue with the mounted volumes?   These containers are running on a Windows 10 box.

**Comment by pmeijer** [comment]
This is not a webgme issue and personally I avoid using docker on windows as there's often issues with it (I don't blame them since it's inherently more complex than running natively on linux).

However since we're moving more towards docker/docker-compose I appreciate your question.
So, this works for me (I'm using windows 10 with the native Hyper-V):
1. Share the C drive with the docker daemon.
![image](https://user-images.githubusercontent.com/6518904/45556127-21b7bb00-b800-11e8-8237-eed16873ee65.png)
2. Before running docker-compose `set COMPOSE_CONVERT_WINDOWS_PATHS=1`
3. Share the volume from the home-directory (this might be the key in your case).  
```
volumes:
      - ~/blob-local-storage:/blob-local-storage
```
4. (This probably works with a full regular windows paths as well and skipping the `COMPOSE..`. However that means you need two different compose.yml for windows/linux.)

FYI Trying this out I ran into:
[Error starting userland proxy}(https://github.com/docker/for-win/issues/573) the fix was to reboot docker.
