### ISSUE TITLE
Reported ZIP Blob Size Incorrect

### ISSUE THREAD

**Issue by rlhelinski** [webgme/webgme#1673]
Related to https://github.com/webgme/webgme/issues/1662 the size of the zip file in the Plug-in Results dialog is incorrect. It appears to be reporting the size of the original artifact.

Example:
![Screenshot_2019-03-15 WebGME](https://user-images.githubusercontent.com/5163049/54458612-033c6900-472a-11e9-9e86-4413415f790d.png)

After downloading the same artifacts, the size of the ``.json`` file is 32.1kB and the size of the ``.zip`` file is 2.5kB.

``config.blob.compressionLevel = 9;`` is set in the active configuration.

**Comment by pmeijer** [comment]
Yes, that's a good point.
The problem here is that the size-info for the artifact is computed and stored at the point where the artifact is created. And at that point (and even when the metadata is presented as in your example) the actual zip file might never have been created.

Therefore the size should be interpreted as being the uncompressed size. I'm not sure if we need to express that more explicitly.
