### ISSUE TITLE
Autorouter setStartPointPrev is not defined

### ISSUE THREAD

**Issue by lattmann** [webgme/webgme#404]
Uncaught TypeError: nnnedge.setStartPointPrev is not a functionAutoRouterGraph._deleteTwoEdgesAt @ AutoRouter.Graph.js:1125
    AutoRouterGraph._simplifyPaths @ AutoRouter.Graph.js:1229
    AutoRouterGraph._optimize @ AutoRouter.Graph.js:2016
    optimizeFn @ AutoRouter.Graph.js:1957

http://editor.dev.webgme.org/?project=ADM&branch=master&node=%2F759732751&visualizer=METAAspect&aspect=All&selection=

MetaEditor - AVM Design Model tab - you may need to switch in between tabs.

**Comment by brollb** [comment]
I believe I know the issue of this bug but I am having a hard time replicating it - I don't see multiple tabs to switch between:

![ar_bug](https://cloud.githubusercontent.com/assets/4982789/8376289/1e862fcc-1bcb-11e5-862d-6b21f769887f.png)

Any idea what I might be missing? Otherwise, we should be able to get the replay events soon (with the recent update to the autorouter worker). If it is not using the most recent branch for some reason, you can also get the replay events by putting a breakpoint on line 188 of AutoRouter.ActionApplier.js and save the output of this._getActionSequence().
