### ISSUE TITLE
Better "run plugin" programmatic interface

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#475]
The `run_plugin` script currently supports being required by another script. However, it has no way of modifying gme config or the plugin config without creating a new file on the filesystem and passing the path (or editing the gme config).

I am suggesting that we break the `main` function into two functions: one with the parsing of the command line and one with the meaningful logic so that it has a more natural programmatic interface.

An example can be seen at https://github.com/brollb/webgme-setup-tool/blob/enable_disable/src/commands/mixins/Enableable/runPlugin.js

If everyone thinks this is a good change, I can easily update webgme's run_plugin.js to reflect the changes in the webgme-setup-tool's runPlugin.js

**Comment by pmeijer** [comment]
Brian, I see your points. However I would say that these changes are better suited in the [nodemanagerbase](https://github.com/webgme/webgme/blob/master/src/plugin/nodemanagerbase.js). Hakan requested some changes there a while back and I added those there (re-instantiating a plugin and changing project) [#456](https://github.com/webgme/webgme/pull/456). 

However I don't see any issues is breaking down the run_plugin.js too. Keep in mind that you may get conflicts due to [#473](https://github.com/webgme/webgme/pull/473).

**Comment by pmeijer** [comment]
Brian if this isn't applicable anymore, remove the Backlog Label.
