### ISSUE TITLE
Naming a pointer 'base' is not allowed

### ISSUE THREAD

**Issue by phreed** [webgme/webgme#892]
Naming a pointer 'base' is not allowed.
There is no indication that 'base' is a reserved word.
Nor is there a compelling reason that it should be reserved.

**Comment by pmeijer** [comment]
![image](https://cloud.githubusercontent.com/assets/6518904/13963739/8876e41a-f034-11e5-8593-98bbea3fba6f.png)

**Comment by phreed** [comment]
Right, that is what happens.
The only indication is that it fails when you try.
This is something of a general problem.
Things turn some shade of red indicating that you cannot do what you are trying but no explanation is provided.

**Comment by pmeijer** [comment]
I think the red is sufficient in this case.

**Comment by pmeijer** [comment]
![image](https://cloud.githubusercontent.com/assets/6518904/14505695/e2b340a2-017f-11e6-8348-9fc1fa16cf37.png)

**Comment by phreed** [comment]
I am puzzled by your response.
There are two sub-issues: 1) no helpful message 2) no compelling reason why 'base' is reserved.
 
1) no helpful message
The example you provided shows a site that provides a description of what is wrong with the field value.
webGME shows no explanation, it just says "red" (meaning wrong), no explanation is provided.
It sounds like you are agreeing that there should be a helpful message?

2) 'base' should not be reserved
No response to this point.

**Comment by pmeijer** [comment]
1) Red is meant to imply that the input is invalid.
2) In this case it is invalid to name it base since it is a reserved pointer name.

I agree in general that "invalid" could be dissected into groups (e.g. reserved, already defined, failing regex) with specialized errors. The same could be applied when creating new projects, branches, etc.

Will reopen the issue, but can't say when this will be implemented.
