### ISSUE TITLE
Extend containment concept

### ISSUE THREAD

**Issue by finger563** [webgme/webgme#940]
I have a use case where I want to specify in the META that an instance in the model (i.e. `node'` which has base type `node` which is in the META) can only contain children whose type is an instance of an instance (i.e. `component'` exists elsewhere in the model as an instance of `component`, which is defined in the meta; I want to enforce that `node'` can only contain _instances_ of `component'` (or other `component'`s defined in the model))

**Comment by finger563** [comment]
Based on discussion with @kecso, this should be possible (and extensible) by adding extra attributes to `containment` which specify for instance if the containment is allowed to contain first children (i.e. objects whose closest node in the inheritance tree exists in the meta) or not.

**Comment by finger563** [comment]
Similarly, if you apply the same logic to the `inheritance` relationship, then you might say that an object `CI` inherits directly from an object `C` defined in the `meta` or you may want to say that `CI` only inherits from _instances_ of `C`, i.e. objects not defined in the `meta`.  This would provide similar capability while allowing you to further extend the attributes of class `C` if need be.

**Comment by kecso** [comment]
Can you describe a bit detailed scenario for the latter 'requirement'?
The inheritance is not a rule in WebGME but an 'attribute' that we leverage.
So, by default there will be items, that inherit from CI and not C, but the question is more like 'what would you want to do with the instances of CI / how you want to restrict the instances of CI'.
I believe if we allow 'special' behavior for the relational rules that can be defined with the Meta, we will cover this scenario as well.

**Comment by kecso** [comment]
During our first discussion we came to the conclusion, that the scenario is specific (even if we would be able to bring up multiple use-cases) and should be solved by constraints rather than specializing generic language concepts.
So the 'workaround' would be to create a constraint for the container node, to check that none of the children of the instance is direct instance of a language concept.

And all of the above requirements should be fulfilled with specialized UI's (or visualizers), rather than specializing the generic one.

**Comment by pmeijer** [comment]
See discussion
